spring.application.name=ecommerce-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=password

# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.validate-migration-naming=true

jwt.secret=8d2e7c4a9f1b6e3d8c5f7a2b9e1d4c6f8a3b5e7d9c1f4a6b8e2d7c9f1a3b5d6
jwt.expiration=3600000

payment.webhook.secret=my-secret

razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key-secret=${RAZORPAY_KEY_SECRET}
razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET}