CREATE TABLE cart
(

    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    CONSTRAINT uk_cart_user
        UNIQUE (user_id),

    CONSTRAINT fk_cart_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
);