CREATE TABLE cart_item
(

    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cart_id    BIGINT  NOT NULL,

    product_id BIGINT  NOT NULL,

    quantity   INTEGER NOT NULL,

    CONSTRAINT fk_cart_item_cart
        FOREIGN KEY (cart_id)
            REFERENCES cart (id),

    CONSTRAINT fk_cart_item_product
        FOREIGN KEY (product_id)
            REFERENCES product (id),

    CONSTRAINT uk_cart_product
        UNIQUE (cart_id, product_id)
);